apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mysql-backup-gcsfuse
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysql-backup-gcsfuse
            image: jonaseck/mysql-backup-gcsfuse
            args:
            - /bin/sh
            - -c
            - >
              mkdir -p /backup &&
              gcsfuse $STORAGE_BACKUP_BUCKET_NAME /backup &&
              mysqldump -p ${MYSQL_USER} -h ${MYSQL_HOST} -p ${MYSQL_PASSWORD} --all-databases | bzip2 > /backup/${BACKUP_PREFIX}-$(date +\%Y.\%m.\%d.\%H\%M\%S).sql.gz
            lifecycle:
              preStop:
                exec:
                  command: ["fusermount", "-u", "/backup"]
            restartPolicy: OnFailure
            env:
            - name: MYSQL_USER
              value: mysql-db
            - name: MYSQL_PASSWORD
              value: mysql-db
            - name: MYSQL_HOST
              value: mysql-db
            - name: STORAGE_BACKUP_BUCKET_NAME
              value: mybucket
            - name: BACKUP_PREFIX
              value: test
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/credentials/google-application-credentials.json"
            volumeMounts:
            - name: google-application-credentials
              mountPath: "/credentials"
              readOnly: true
          volumes:
          - name: google-application-credentials
            secret:
              secretName: google-application-credentials